### ISSUE TITLE
connection error aborted

### ISSUE THREAD

**Issue by sousasag** [telmonteiro/PEEC-24#4]
I got several connection error when downloading the files. The good think is that the files that were downloaded were kept in the disk and it recognizes it. It should be nice to address this problem automatically.

```
...
  File "/home/sousasag/Programas/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by telmonteiro** [comment]
Added a function (download_spectra) to retry the download (eso.retrieve_data) in the case of a connection error. As I didn't have connection issues so far, I am not 100% sure it solves the problem.
