### ISSUE TITLE
Type error, crash

### ISSUE THREAD

**Issue by sousasag** [telmonteiro/PEEC-24#8]
Running with the default settings:

Processing the data...
Traceback (most recent call last):
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA_run.py", line 35, in <module>
    SAITAMA(stars, instruments, indices, max_spectra, min_snr, download, neglect_data, username_eso, download_path, final_path)
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA.py", line 347, in SAITAMA
    results, gaps, flag_period, period, period_err, harmonics_list, amplitude, amplitude_err = gls(star_name, instr, bjd-2450000, I_CaII, y_err=I_CaII_err, 
                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: gls() missing 1 required positional argument: 'y'

**Comment by telmonteiro** [comment]
Solved!

**Comment by sousasag** [comment]
Now I have another one:

Processing the data...
Traceback (most recent call last):
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA_run.py", line 35, in <module>
    SAITAMA(stars, instruments, indices, max_spectra, min_snr, download, neglect_data, username_eso, download_path, final_path)
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA.py", line 358, in SAITAMA
    smw, smw_err, log_rhk, log_rhk_err, prot_n84, prot_n84_err, prot_m08, prot_m08_err, age_m08, age_m08_err = get_calibrations_CaII(star_gaia_dr3,instr,I_CaII,I_CaII_err)
                                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/pipeline_functions/general_funcs.py", line 393, in get_calibrations_CaII
    bv, bv_err, bv_ref = get_bv(star_gaia_dr3, alerts=True) 
    ^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 3)

**Comment by sousasag** [comment]
I used the following to fix this error (file general_funcs.py):

```
    #get B-V from SIMBAD, if none get from Ballesteros calibration
    try:
        bv, bv_err, bv_ref = get_bv(star_gaia_dr3, alerts=True) 
    except:
        b = pyasl.BallesterosBV_T()
        bv = b.t2bv(T=teff) 

    if math.isnan(bv) == True:
        b = pyasl.BallesterosBV_T()
        bv = b.t2bv(T=teff) 
```
